steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
      - -c
      - echo "Secret is $$SECRET_KEY"
  secretEnv: ['SECRET_KEY']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ["-c","docker build -t gcr.io/dtu-mlops-338110/testing --build-arg SECRET_KEY=$$SECRET_KEY -f CloudBuild_Dockerfile ."]
  secretEnv: ['SECRET_KEY']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtu-mlops-338110/testing']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ["-c","docker run gcr.io/dtu-mlops-338110/testing:latest"]
availableSecrets:
  secretManager:
  - versionName: projects/310452010967/secrets/SECRET_KEY/versions/latest
    env: 'SECRET_KEY'
timeout: 1200s