steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
      - -c
      - echo "Secret is $$SECRET_KEY"
  secretEnv: ['SECRET_KEY']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['echo', ${_SUB_VALUE}]
substitutions:
    _SUB_VALUE: unused
options:
    substitution_option: 'ALLOW_LOOSE'
# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args: 
#       - -c
#       - echo "Secret is ${_KEY}"
#   secretEnv: ['SECRET_KEY']ker'
# substitutions: 
#   _KEY: $$SECRET_KEY
# options:
#     dynamic_substitutions: true
# - name: 'gcr.io/cloud-builders/docker'
#   args: ["build", "-t", "gcr.io/dtu-mlops-338110/testing","--build-arg", "SECRET_KEY=${_KEY}", "."]
#   secretEnv: ['SECRET_KEY']
# substitutions: 
#   _KEY: $$SECRET_KEY
# options:
#     dynamic_substitutions: true
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtu-mlops-338110/testing']
availableSecrets:
  secretManager:
  - versionName: projects/310452010967/secrets/SECRET_KEY/versions/latest
    env: 'SECRET_KEY'
timeout: 1200s